Echo statements added

diff --git a/.github/workflows/CI_DSSAT.yml b/.github/workflows/CI_DSSAT.yml
--- a/.github/workflows/CI_DSSAT.yml
+++ b/.github/workflows/CI_DSSAT.yml
@@ -80,13 +80,17 @@ jobs:
             any::readr
             any::tidyr
 
-      - name: Find RCroptest
+      - name: Find RCroptest & others
         run: |
           RCROPPATH=$(find . -type d -name RCroptest | head -n 1)
           pwd
           echo "Found RCroptest at: $RCROPPATH"
-          find . -type d -name workA
-          find . -type d -name workB
+          
+          echo "Searching for 'workA' directory:"
+          find . -type d -name workA || echo " workA not found."
+
+          echo "Searching for 'workB' directory:"
+          find . -type d -name workB || echo "workB not found."
            
       - name: Verify installation
         run: |
